#!/bin/bash -x

curl_all() {
    curl 127.0.0.1:3000 > dist/index.html
    for i in {1..12};
    do
        curl 127.0.0.1:3000/data/$i > dist/data/$i.html
    done
}

node src/server.js &
echo "this will take a sec"
sleep 4
$(curl_all)
kill $!
node tst.js
